services:
  app1:
    env_file: "env/app1.env"
    build: .
    ports:
      - '8081:8081'
    networks:
      - app1-network

# Defining a custom network. This network will be used for hosting app1 and app2
networks:
  app1-network:
    name: app1-network