apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-csi-fuse
  namespace: my-space
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: example-storage-class