apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  containers:
    - name: alpine-container
      image: alpine
      stdin: true
      tty: true
      command: ["/bin/sh"]
      volumeMounts:
        - name: app1-config-vol
          mountPath: "/config"
          readOnly: true
  volumes:
    - name: app1-config-vol
      configMap:
        name: app1-config
  restartPolicy: Never


