apiVersion: v1
kind: Service
metadata:
  name: app1-service-cloud-sql-fuse
  namespace: my-space
spec:
  selector:
    app: first-app-cloud-sql-fuse
  ports:
    - protocol: 'TCP'
      port: 8081
      targetPort: 8081
  type: LoadBalancer